/**
  * @file      Tests for App.js
  * @author    Auto-Generated By React
  * @version   1.0.0
  * @since     1.0.0
*/

/* 
==============================================================
  DEPENDENCIES and VARIABLES
============================================================== 
*/

import { render, screen } from '@testing-library/react';
import App from './App';

/* 
==============================================================
  TEST(S)
============================================================== 
*/

test('renders learn react link', () => {
  render(<App />);
  const linkElement = screen.getByText(/learn react/i);
  expect(linkElement).toBeInTheDocument();
});

/*
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  END OF FILE
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
*/